### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by chenxiaolonghao** [ShermanTsang/ShareManBox-Nuxt#2]
项目下载后先用yarm install安装包，然后使用npm run dev运行项目出现了图片上的错误，是服务器停了吗?非常喜欢这个项目，希望您看到后给予回复，谢谢
![微信图片_20210324172007](https://user-images.githubusercontent.com/20189970/112285356-31fc5b00-8cc5-11eb-8bbf-41f11e2d12d0.png)

**Comment by ShermanTsang** [comment]
后端服务升级了哈前段时间，你应该刚好碰到调整时间了。
[](https://share-man.com/page/log)

**Comment by ShermanTsang** [comment]
[升级详情](https://share-man.com/page/log)
